<?php

/**
 * Implements hook_field_formatter_info().
 */

function toggle_summary_field_formatter_info(){
  return array(
    'toggle_summary' => array(
      'label' => t('Summary/Trimmed Toggle'),
      'field types' => array('text_with_summary'),
      'settings' => array('trim_length' => 600),
    )
  );
}

/**
 * Implements hook_field_formatter_settings_form().
 */
function toggle_summary_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];

  $element = array();

  if($display['type'] == 'toggle_summary') {
    $element['trim_length'] = array(
      '#title' => t('Trim length'),
      '#type' => 'textfield',
      '#size' => 10,
      '#default_value' => $settings['trim_length'],
      '#element_validate' => array('element_validate_integer_positive'),
      '#required' => TRUE,
    );
  }

  return $element;
}

/**
 * Implements hook_field_formatter_settings_summary().
 */

function toggle_summary_field_formatter_settings_summary($field, $instance, $view_mode) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];

  $summary = '';

  if($display['type'] == 'toggle_summary') {
    $summary = t('Trim length') . ': ' . $settings['trim_length'];
  }

  return $summary;
}


/**
 * Implements hook_field_formmater_view().
 */
function toggle_summary_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display){
  $element = array();
  $settings = $display['settings'];

  if($display['type'] == 'toggle_summary') {
    foreach ($items as $delta => $item) {
      $full = _text_sanitize($instance, $langcode, $item, 'value');
      if (!empty($item['summary'])) {
        $summary = _text_sanitize($instance, $langcode, $item, 'summary');
      }
      else {
        $summary = $full;
        $summary = text_summary($output, $instance['settings']['text_processing'] ? $item['format'] : NULL, $display['settings']['trim_length']);
      }
      $summary .= 'Working!';
      $element[$delta] = array('#markup' => $summary);
    }
  }
  return $element;
}
